format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch\
$fill\
$nodejs\
$dotnet\
$python\
$java\
$c\
$cmd_duration\
$shell\
$time\
$username\
$line_break\
$character\
"""

add_newline = true # Adds newline for structured prompt

[character]
success_symbol = "[➜](fg:#04d1f9)" # Tokyo Night blue
error_symbol = "[✗](fg:#ff6ac1)"   # Tokyo Night pink
format = "$symbol "                # Clean, no extra lines

[directory]
style = "fg:#58c6ff"    # Tokyo Night cyan
truncation_length = 2
truncate_to_repo = true
format = "$path "       # Simple, warning-free
home_symbol = "~"

[git_branch]
style = "fg:#dddddd"
symbol = " "
format = "$symbol$branch "

[git_status]
style = "fg:#ff6ac1"
format = "$all_status "
