#!/bin/bash

borders \
  style=round \
  width=4.0 \
  hidpi=on \
  active_color=0xff89b4fa \    # Blue-ish pastel for active
inactive_color=0x802c2e34 \    # Subtle gray with transparency
background_color=0x202c2e34 \  # Slightly transparent background
blur_radius=20
